In [115]:
## Задание на повторение материала

In [116]:
## 1

In [117]:
import numpy as np

In [118]:
a = np.array([i for i in range(12,24)])

In [119]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [120]:
## 2

In [121]:
b11 = np.reshape(a, (2, 6))

In [122]:
b11

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [123]:
b12 = np.reshape(a, (6, 2))

In [124]:
b12

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [125]:
b13 = np.reshape(a[0:8], (2,4))

In [126]:
b13

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [127]:
b14 = np.reshape(a[0:8], (4,2))

In [128]:
b14

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [129]:
b15 = np.reshape(a[0:6], (3,2))

In [130]:
b15

array([[12, 13],
       [14, 15],
       [16, 17]])

In [131]:
## 3

In [132]:
b21 = np.reshape(a[0:4], (2,-1))

In [133]:
b21

array([[12, 13],
       [14, 15]])

In [134]:
b22 = np.reshape(a[0:4], (-1,2))

In [135]:
b22

array([[12, 13],
       [14, 15]])

In [136]:
b23 = np.reshape(a[0:6], (2,-1))

In [137]:
b23

array([[12, 13, 14],
       [15, 16, 17]])

In [138]:
b24 = np.reshape(a[0:6], (-1,2))

In [139]:
b24

array([[12, 13],
       [14, 15],
       [16, 17]])

In [140]:
b25 = np.reshape(a[0:8], (2,-1))

In [141]:
b25

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [142]:
## 4

In [143]:
## да, массив, состоящий из одного столбца и 12 строк является одномерным.

In [144]:
## 5

In [145]:
new_a = np.random.randn(3,4)

In [146]:
new_a

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975]])

In [147]:
np.size(new_a)

12

In [148]:
upd_a = new_a.reshape(1,np.size(new_a))

In [149]:
upd_a

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
        -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
        -0.46341769, -0.46572975]])

In [150]:
## 6

In [151]:
a_6 = np.arange(20, 0, -2)

In [152]:
a_6

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [153]:
a_6.shape

(10,)

In [154]:
## 7

In [155]:
b_7 = np.reshape(np.arange(20, 1, -2), (1, 10))

In [156]:
b_7

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [157]:
b_7.shape

(1, 10)

In [158]:
## разница в массиве из 6го и 7го номера в их формах, чтобы создать 1 на 10 массив нужно было дополнительно применить команду reshape

In [159]:
## 8

In [160]:
a_8 = np.zeros((2,2))

In [161]:
b_8 = np.ones((3,2))

In [162]:
v = np.vstack((a_8,b_8))

In [163]:
np.size(v)

10

In [164]:
## 9

In [165]:
a_9 = np.arange(0,12,1)

In [166]:
A = np.reshape(a_9, (4,3))

In [167]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [168]:
At = A.transpose()

In [169]:
B = np.dot(A, At)

In [170]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [171]:
B.shape

(4, 4)

In [172]:
np.linalg.matrix_rank(B)

2

In [178]:
np.linalg.det(B)

0.0

In [179]:
## поскольку детерминант матрицы В равен нулю-перед нами сингулярная матрица, обратить которую невозможно (можно попробовать это сделать и получим от питона ошибку)

In [180]:
## 10

In [183]:
np.random.seed(42)

In [184]:
a_10 = np.random.randint(0,10,3)

In [185]:
a_10

array([6, 3, 7])

In [210]:
## 11

In [216]:
c = np.random.uniform(low=0, high=16, size=(16,)).astype(int)

In [217]:
c

array([ 0, 13, 11, 11, 12,  1,  5,  1, 13,  9,  5,  1,  4,  5, 11, 10])

In [231]:
## 12

In [232]:
C = np.reshape(c, (4,4))

In [233]:
C

array([[ 0, 13, 11, 11],
       [12,  1,  5,  1],
       [13,  9,  5,  1],
       [ 4,  5, 11, 10]])

In [234]:
D = np.add(B, np.dot(C,10))

In [235]:
D

array([[  5, 144, 133, 142],
       [134,  60, 136, 132],
       [153, 176, 199, 222],
       [ 72, 172, 322, 402]])

In [236]:
np.linalg.det(D)

122146000.0

In [237]:
np.linalg.matrix_rank(D)

4

In [251]:
D_inv = np.linalg.inv(D)

In [252]:
## 13

In [253]:
D_inv

array([[-0.00782506, -0.0006674 ,  0.00806936, -0.00147299],
       [ 0.00358833, -0.00860167,  0.00903034, -0.00342999],
       [ 0.02811226,  0.03647176, -0.0304714 , -0.00507851],
       [-0.02265158, -0.02541385,  0.01909846,  0.0082868 ]])

In [254]:
## 14

In [255]:
D_inv[np.where(D_inv<0)]=0

In [256]:
D_inv

array([[0.        , 0.        , 0.00806936, 0.        ],
       [0.00358833, 0.        , 0.00903034, 0.        ],
       [0.02811226, 0.03647176, 0.        , 0.        ],
       [0.        , 0.        , 0.01909846, 0.0082868 ]])

In [257]:
D_inv[np.where(D_inv>0)]=1

In [258]:
D_inv

array([[0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.]])

In [259]:
E = np.where([[False,False,True,False],[True,False,True,False],[True,True,False,False],[False,False,True,True]],B,C)

In [260]:
E

array([[  0,  13,  23,  11],
       [ 14,   1,  86,   1],
       [ 23,  86,   5,   1],
       [  4,   5, 212, 302]])